kind: pipeline
name: default
steps:
- name: docker-build
  image: plugins/docker
  settings:
    repo: derek82511/node-rpc-queue-cleaner-rabbitmq
    tags:
      - latest
      - ${DRONE_TAG}
    username:
      from_secret: docker_io_username
    password:
      from_secret: docker_io_password
trigger:
  event:
  - tag
